### ISSUE TITLE
Do you want to be listed on awesome-computercraft?

### ISSUE THREAD

**Issue by tomodachi94** [aspen-reeves/awesome-switchcraft#12]
Hey @aspen-reeves, awesome project (pun intended!)

I'm the maintainer of [awesome-computercraft](https://github.com/tomodachi94/awesome-computercraft), and I'd love to list this in the `Other lists` section on the list I maintain.

Is that alright?

**Comment by aspen-reeves** [comment]
ok

**Comment by tomodachi94** [comment]
Done.
