### ISSUE TITLE
bigfont need not be listed

### ISSUE THREAD

**Issue by hugeblank** [aspen-reeves/awesome-switchcraft#4]
I feel like adding bigfont to [the list](https://github.com/aspen-reeves/awesome-switchcraft/blob/main/README.md?plain=1#L45) implies that it may need to be downloaded, but SC3 provides it in the [ROM](https://docs.sc3.io/faq/rom.html#apis). I propose removing it, and/or including some kind of tips and tricks page that mentions this, as it's a little known fact.

**Comment by aspen-reeves** [comment]
i added a "builtins" section, and added all of the rom programs there. see commit 4264056
